language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saschascata/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saschascata/react-test npm test

after_success:
  - docker build -t saschascata/multi-client ./client
  - docker build -t saschascata/multi-nginx ./nginx
  - docker build -t saschascata/multi-server ./server
  - docker build -t saschascata/multi-worker ./worker
  #Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to dockerhub
  - docker push saschascata/multi-client
  - docker push saschascata/multi-nginx
  - docker push saschascata/multi-server
  - docker push saschascata/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-117101198990
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
